CONNECT system/Oracle123@//localhost:1521/XEPDB1;
DROP INDEX biblioteca.IDX_UN_BLOQUEO_ACTIVO;
CREATE UNIQUE INDEX biblioteca.IDX_UN_BLOQUEO_ACTIVO ON biblioteca.BLOQUEO (CASE WHEN ESTADO = 'ACTIVO' THEN ID_SOCIO ELSE NULL END);
EXIT;
