-- ==========================================
-- SCRIPT MAESTRO DE INICIALIZACIÓN
-- Todos los objetos se crean en el esquema biblioteca
-- ==========================================


-- ==========================================
-- db/01_schema.sql
-- ==========================================

-- Creación de usuario y permisos (Ejecutar como SYSTEM si no se usa el script de inicio del contenedor)
-- En gvenzl/oracle-xe, el usuario APP_USER ya se crea con las variables de entorno.

-- ==========================================
-- 1. TABLAS PRINCIPALES
-- ==========================================

-- SOCIO
CREATE TABLE biblioteca.SOCIO (
    ID_SOCIO NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    USUARIO VARCHAR2(50) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR2(255) NOT NULL,
    ROL VARCHAR2(20) CHECK (ROL IN ('SOCIO', 'BIBLIOTECARIO', 'ADMIN')) NOT NULL,
    PENALIZACION_HASTA DATE,
    MAX_PRESTAMOS_ACTIVOS NUMBER DEFAULT 3 NOT NULL,
    NOMBRE VARCHAR2(100),
    EMAIL VARCHAR2(100)
);

-- LIBRO (La obra)
CREATE TABLE biblioteca.LIBRO (
    ID_LIBRO NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ISBN VARCHAR2(20) UNIQUE NOT NULL,
    TITULO VARCHAR2(200) NOT NULL,
    AUTOR VARCHAR2(100) NOT NULL,
    CATEGORIA VARCHAR2(50),
    ANIO NUMBER(4)
);

-- EJEMPLAR (Copia física)
CREATE TABLE biblioteca.EJEMPLAR (
    ID_EJEMPLAR NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ID_LIBRO NUMBER NOT NULL,
    CODIGO_BARRAS VARCHAR2(50) UNIQUE NOT NULL,
    ESTADO VARCHAR2(20) CHECK (ESTADO IN ('DISPONIBLE', 'BLOQUEADO', 'PRESTADO', 'BAJA')) NOT NULL,
    UBICACION VARCHAR2(100),
    VERSION NUMBER DEFAULT 0,  -- Control de concurrencia optimista (JPA @Version)
    CONSTRAINT FK_EJEMPLAR_LIBRO FOREIGN KEY (ID_LIBRO) REFERENCES biblioteca.LIBRO(ID_LIBRO)
);

-- BLOQUEO (Reserva 1 día)
CREATE TABLE biblioteca.BLOQUEO (
    ID_BLOQUEO NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ID_SOCIO NUMBER NOT NULL,
    ID_EJEMPLAR NUMBER NOT NULL,
    FECHA_INICIO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FECHA_FIN TIMESTAMP NOT NULL, -- Se calculará como FECHA_INICIO + 1 día
    ESTADO VARCHAR2(20) CHECK (ESTADO IN ('ACTIVO', 'CANCELADO', 'EXPIRADO', 'CONVERTIDO')) NOT NULL,
    CONSTRAINT FK_BLOQUEO_SOCIO FOREIGN KEY (ID_SOCIO) REFERENCES biblioteca.SOCIO(ID_SOCIO),
    CONSTRAINT FK_BLOQUEO_EJEMPLAR FOREIGN KEY (ID_EJEMPLAR) REFERENCES biblioteca.EJEMPLAR(ID_EJEMPLAR)
);

-- PRESTAMO
CREATE TABLE biblioteca.PRESTAMO (
    ID_PRESTAMO NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ID_SOCIO NUMBER NOT NULL,
    ID_EJEMPLAR NUMBER NOT NULL,
    FECHA_PRESTAMO DATE DEFAULT SYSDATE NOT NULL,
    FECHA_PREVISTA_DEVOLUCION DATE NOT NULL,
    FECHA_DEVOLUCION_REAL DATE,
    ESTADO VARCHAR2(20) CHECK (ESTADO IN ('ACTIVO', 'DEVUELTO')) NOT NULL,
    ID_BLOQUEO NUMBER, -- Opcional, si viene de un bloqueo
    CONSTRAINT FK_PRESTAMO_SOCIO FOREIGN KEY (ID_SOCIO) REFERENCES biblioteca.SOCIO(ID_SOCIO),
    CONSTRAINT FK_PRESTAMO_EJEMPLAR FOREIGN KEY (ID_EJEMPLAR) REFERENCES biblioteca.EJEMPLAR(ID_EJEMPLAR),
    CONSTRAINT FK_PRESTAMO_BLOQUEO FOREIGN KEY (ID_BLOQUEO) REFERENCES biblioteca.BLOQUEO(ID_BLOQUEO)
);

-- ==========================================
-- 2. ÍNDICES RECOMENDADOS
-- ==========================================
CREATE INDEX biblioteca.IDX_EJEMPLAR_LIBRO ON biblioteca.EJEMPLAR (ID_LIBRO);
CREATE INDEX biblioteca.IDX_BLOQUEO_SOCIO ON biblioteca.BLOQUEO (ID_SOCIO);
CREATE INDEX biblioteca.IDX_BLOQUEO_EJEMPLAR ON biblioteca.BLOQUEO (ID_EJEMPLAR);
CREATE INDEX biblioteca.IDX_PRESTAMO_SOCIO ON biblioteca.PRESTAMO (ID_SOCIO);
CREATE INDEX biblioteca.IDX_PRESTAMO_EJEMPLAR ON biblioteca.PRESTAMO (ID_EJEMPLAR);

-- SEGURIDAD: ÍNDICE ÚNICO CONDICIONAL
-- Garantiza físicamente que un socio solo tenga 1 bloqueo ACTIVO a la vez.
-- Protege contra condiciones de carrera que los triggers no pueden ver.
CREATE UNIQUE INDEX biblioteca.IDX_UN_BLOQUEO_ACTIVO 
ON biblioteca.BLOQUEO (CASE WHEN ESTADO = 'ACTIVO' THEN ID_SOCIO ELSE NULL END);



-- ==========================================
-- db/02_triggers.sql
-- ==========================================

-- ==========================================
-- 3. TRIGGERS DE REGLAS DE NEGOCIO
-- ==========================================

-- 3.1 Trigger para validar BLOQUEO
-- Un socio solo puede tener 1 bloqueo ACTIVO Y NO EXPIRADO.
-- El ejemplar debe estar DISPONIBLE.
CREATE OR REPLACE TRIGGER biblioteca.TRG_VALIDAR_BLOQUEO
BEFORE INSERT ON biblioteca.biblioteca.BLOQUEO FOR EACH ROW
DECLARE
    v_count_bloqueos NUMBER;
    v_estado_ejemplar EJEMPLAR.ESTADO%TYPE;
BEGIN
    -- 1. Verificar si el socio ya tiene un bloqueo ACTIVO que NO haya expirado
    -- SEGURIDAD M-01: Sincronizado con lógica Java - también verificar FECHA_FIN
    SELECT COUNT(*)
    INTO v_count_bloqueos
    FROM biblioteca.BLOQUEO
    WHERE ID_SOCIO = :NEW.ID_SOCIO
      AND ESTADO = 'ACTIVO'
      AND FECHA_FIN > SYSDATE;  -- Solo contar bloqueos no expirados

    IF v_count_bloqueos > 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'El socio ya tiene un bloqueo ACTIVO. Solo se permite uno.');
    END IF;

    -- 2. Verificar disponibilidad del ejemplar
    SELECT ESTADO
    INTO v_estado_ejemplar
    FROM biblioteca.EJEMPLAR
    WHERE ID_EJEMPLAR = :NEW.ID_EJEMPLAR;

    IF v_estado_ejemplar != 'DISPONIBLE' THEN
        RAISE_APPLICATION_ERROR(-20002, 'El ejemplar no está DISPONIBLE para bloqueo.');
    END IF;
    
    -- Si todo ok, establecer FECHA_FIN a 1 día después si no viene informada (aunque debería venir de lógica, aseguramos)
    IF :NEW.FECHA_FIN IS NULL THEN
        :NEW.FECHA_FIN := :NEW.FECHA_INICIO + 1;
    END IF;
END;
/

-- 3.2 Trigger para actualizar estado de ejemplar al BLOQUEAR
-- NOTA: El estado debe ser 'BLOQUEADO' para coincidir con el CHECK constraint del schema
CREATE OR REPLACE TRIGGER biblioteca.TRG_ACTUALIZAR_EJEMPLAR_BLOQUEO
AFTER INSERT ON biblioteca.biblioteca.BLOQUEO FOR EACH ROW
BEGIN
    UPDATE biblioteca.EJEMPLAR SET ESTADO = 'BLOQUEADO'
    WHERE ID_EJEMPLAR = :NEW.ID_EJEMPLAR;
END;
/


-- 3.3 Trigger OBLIGATORIO: Inserción de PRÉSTAMO
CREATE OR REPLACE TRIGGER biblioteca.TRG_VALIDAR_PRESTAMO
BEFORE INSERT ON biblioteca.biblioteca.PRESTAMO FOR EACH ROW
DECLARE
    v_penalizacion DATE;
    v_prestamos_activos NUMBER;
    v_estado_ejemplar EJEMPLAR.ESTADO%TYPE;
    v_max_prestamos NUMBER;
    v_bloqueo_socio NUMBER;
BEGIN
    -- 1. Socio penalizado
    SELECT PENALIZACION_HASTA, MAX_PRESTAMOS_ACTIVOS
    INTO v_penalizacion, v_max_prestamos
    FROM biblioteca.SOCIO
    WHERE ID_SOCIO = :NEW.ID_SOCIO;

    IF v_penalizacion IS NOT NULL AND v_penalizacion > SYSDATE THEN
        RAISE_APPLICATION_ERROR(-20003, 'El socio está penalizado hasta ' || TO_CHAR(v_penalizacion, 'DD/MM/YYYY HH24:MI'));
    END IF;

    -- 2. Límite máximo de préstamos activos
    SELECT COUNT(*)
    INTO v_prestamos_activos
    FROM biblioteca.PRESTAMO
    WHERE ID_SOCIO = :NEW.ID_SOCIO
      AND ESTADO = 'ACTIVO';

    IF v_prestamos_activos >= v_max_prestamos THEN
        RAISE_APPLICATION_ERROR(-20004, 'El socio ha alcanzado el límite máximo de préstamos activos (' || v_max_prestamos || ').');
    END IF;

    -- 3. Ejemplar no disponible
    SELECT ESTADO
    INTO v_estado_ejemplar
    FROM biblioteca.EJEMPLAR
    WHERE ID_EJEMPLAR = :NEW.ID_EJEMPLAR;

    IF v_estado_ejemplar = 'PRESTADO' THEN
        RAISE_APPLICATION_ERROR(-20005, 'El ejemplar ya está PRESTADO.');
    ELSIF v_estado_ejemplar = 'BAJA' THEN
        RAISE_APPLICATION_ERROR(-20006, 'El ejemplar está de BAJA.');
    ELSIF v_estado_ejemplar = 'BLOQUEADO' THEN
        -- Permitir solo si el bloqueo ACTIVO pertenece a ese socio Y NO HA EXPIRADO
        -- SEGURIDAD C-01: Defensa en profundidad. Validación temporal estricta desencadenada por BD.
        SELECT COUNT(*)
        INTO v_bloqueo_socio
        FROM biblioteca.BLOQUEO
        WHERE ID_EJEMPLAR = :NEW.ID_EJEMPLAR
          AND ID_SOCIO = :NEW.ID_SOCIO
          AND ESTADO = 'ACTIVO'
          AND FECHA_FIN > SYSDATE;
        
        IF v_bloqueo_socio = 0 THEN
             RAISE_APPLICATION_ERROR(-20007, 'El ejemplar está BLOQUEADO por otro socio o el bloqueo ha expirado.');
        END IF;
    END IF;

    -- Si pasa las validaciones, el trigger POST-INSERT actualizará el estado
END;
/

-- 3.4 Trigger POST-INSERT PRESTAMO para actualizar estados
CREATE OR REPLACE TRIGGER biblioteca.TRG_ACTUALIZAR_ESTADOS_PRESTAMO
AFTER INSERT ON biblioteca.biblioteca.PRESTAMO FOR EACH ROW
BEGIN
    -- Cambiar estado del ejemplar
    UPDATE biblioteca.EJEMPLAR SET ESTADO = 'PRESTADO'
    WHERE ID_EJEMPLAR = :NEW.ID_EJEMPLAR;

    -- Si había bloqueo activo para este ejemplar y socio, marcarlo como CONVERTIDO
    UPDATE biblioteca.BLOQUEO SET ESTADO = 'CONVERTIDO'
    WHERE ID_EJEMPLAR = :NEW.ID_EJEMPLAR
      AND ID_SOCIO = :NEW.ID_SOCIO
      AND ESTADO = 'ACTIVO';
END;
/

-- 3.5 Trigger al DEVOLVER préstamo
CREATE OR REPLACE TRIGGER biblioteca.TRG_DEVOLUCION_PRESTAMO
BEFORE UPDATE ON biblioteca.biblioteca.PRESTAMO FOR EACH ROW
BEGIN
    IF :OLD.ESTADO = 'ACTIVO' AND :NEW.ESTADO = 'DEVUELTO' THEN
        -- Establecer fecha real si no viene
        IF :NEW.FECHA_DEVOLUCION_REAL IS NULL THEN
            :NEW.FECHA_DEVOLUCION_REAL := SYSDATE;
        END IF;
        
        -- Liberar ejemplar
        UPDATE biblioteca.EJEMPLAR SET ESTADO = 'DISPONIBLE'
        WHERE ID_EJEMPLAR = :NEW.ID_EJEMPLAR;
    END IF;
END;
/



-- ==========================================
-- db/04_update_passwords.sql
-- ==========================================

-- Update passwords to 'password' (hash: $2a$10$BA0QvPo6W1sgf2kx7g9C/ulfV.CI8lmDJ/HJczwPrEtOPPAwsePdW)
UPDATE biblioteca.SOCIO SET PASSWORD_HASH = '$2a$10$BA0QvPo6W1sgf2kx7g9C/ulfV.CI8lmDJ/HJczwPrEtOPPAwsePdW';
COMMIT;



-- ==========================================
-- db/05_seed.sql
-- ==========================================

-- Datos de prueba

-- Usuarios
-- Password hash para 'password' (ejemplo BCrypt, aunque aquí pondremos un placeholder si no lo generamos desde Java)
-- En producción usar hashes reales. Aquí usaremos texto plano temporalmente o un hash fijo conocido.
-- Supongamos que $2a$10$Xavi... es el hash de '1234'
INSERT INTO biblioteca.SOCIO (USUARIO, PASSWORD_HASH, ROL, NOMBRE, EMAIL) VALUES ('admin', '$2a$10$BA0QvPo6W1sgf2kx7g9C/ulfV.CI8lmDJ/HJczwPrEtOPPAwsePdW', 'ADMIN', 'Administrador', 'admin@biblio.com');
INSERT INTO biblioteca.SOCIO (USUARIO, PASSWORD_HASH, ROL, NOMBRE, EMAIL) VALUES ('biblio', '$2a$10$BA0QvPo6W1sgf2kx7g9C/ulfV.CI8lmDJ/HJczwPrEtOPPAwsePdW', 'BIBLIOTECARIO', 'Bibliotecario Jefe', 'biblio@biblio.com');
INSERT INTO biblioteca.SOCIO (USUARIO, PASSWORD_HASH, ROL, NOMBRE, EMAIL) VALUES ('socio1', '$2a$10$BA0QvPo6W1sgf2kx7g9C/ulfV.CI8lmDJ/HJczwPrEtOPPAwsePdW', 'SOCIO', 'Juan Socio', 'juan@email.com');

-- Libros
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-0134685991', 'Effective Java', 'Joshua Bloch', 'Tecnología', 2018);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-0321125217', 'Domain-Driven Design', 'Eric Evans', 'Tecnología', 2003);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-8401020414', 'Dune', 'Frank Herbert', 'Ciencia Ficción', 1965);

-- Ejemplares
-- Effective Java (2 copias)
INSERT INTO biblioteca.EJEMPLAR (ID_LIBRO, CODIGO_BARRAS, ESTADO, UBICACION) VALUES (1, 'EJ-001', 'DISPONIBLE', 'Estantería A1');
INSERT INTO biblioteca.EJEMPLAR (ID_LIBRO, CODIGO_BARRAS, ESTADO, UBICACION) VALUES (1, 'EJ-002', 'DISPONIBLE', 'Estantería A1');

-- DDD (1 copia)
INSERT INTO biblioteca.EJEMPLAR (ID_LIBRO, CODIGO_BARRAS, ESTADO, UBICACION) VALUES (2, 'EJ-003', 'DISPONIBLE', 'Estantería B2');

-- Dune (1 copia)
INSERT INTO biblioteca.EJEMPLAR (ID_LIBRO, CODIGO_BARRAS, ESTADO, UBICACION) VALUES (3, 'EJ-004', 'DISPONIBLE', 'Estantería C3');

COMMIT;



-- ==========================================
-- db/06_more_seed.sql
-- ==========================================

-- Extended Seed Data

-- 1. More Books
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-0451524935', '1984', 'George Orwell', 'Ciencia Ficción', 1949);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-0061120084', 'To Kill a Mockingbird', 'Harper Lee', 'Clásico', 1960);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-0743273565', 'The Great Gatsby', 'F. Scott Fitzgerald', 'Clásico', 1925);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-0553380163', 'A Brief History of Time', 'Stephen Hawking', 'Ciencia', 1988);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-0132350884', 'Clean Code', 'Robert C. Martin', 'Tecnología', 2008);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-0201633610', 'Design Patterns', 'Erich Gamma', 'Tecnología', 1994);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-1491950357', 'Building Microservices', 'Sam Newman', 'Tecnología', 2015);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-0307474278', 'The Da Vinci Code', 'Dan Brown', 'Misterio', 2003);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-0547928227', 'The Hobbit', 'J.R.R. Tolkien', 'Fantasía', 1937);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-0439023481', 'The Hunger Games', 'Suzanne Collins', 'Fantasía', 2008);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-0385504201', 'The Da Vinci Code', 'Dan Brown', 'Thriller', 2003);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-0140449136', 'Crime and Punishment', 'Fyodor Dostoevsky', 'Clásico', 1866);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-0679783268', 'Pride and Prejudice', 'Jane Austen', 'Romance', 1813);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-0747532743', 'Harry Potter and the Philosophers Stone', 'J.K. Rowling', 'Fantasía', 1997);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-0062315007', 'The Alchemist', 'Paulo Coelho', 'Ficción', 1988);

-- 2. Copies (Ejemplares)
-- Assuming IDs continue from previous seed (1, 2, 3 were used). New books start at 4.
-- We'll just insert blindly assuming auto-increment works or we can use subqueries if needed, but simple inserts are fine for this demo.

-- 1984
INSERT INTO biblioteca.EJEMPLAR (ID_LIBRO, CODIGO_BARRAS, ESTADO, UBICACION) VALUES ((SELECT ID_LIBRO FROM biblioteca.LIBRO WHERE TITULO='1984'), 'EJ-1984-1', 'DISPONIBLE', 'Estantería F1');
INSERT INTO biblioteca.EJEMPLAR (ID_LIBRO, CODIGO_BARRAS, ESTADO, UBICACION) VALUES ((SELECT ID_LIBRO FROM biblioteca.LIBRO WHERE TITULO='1984'), 'EJ-1984-2', 'DISPONIBLE', 'Estantería F1');

-- Clean Code
INSERT INTO biblioteca.EJEMPLAR (ID_LIBRO, CODIGO_BARRAS, ESTADO, UBICACION) VALUES ((SELECT ID_LIBRO FROM biblioteca.LIBRO WHERE TITULO='Clean Code'), 'EJ-CLEAN-1', 'DISPONIBLE', 'Estantería T1');

-- Design Patterns
INSERT INTO biblioteca.EJEMPLAR (ID_LIBRO, CODIGO_BARRAS, ESTADO, UBICACION) VALUES ((SELECT ID_LIBRO FROM biblioteca.LIBRO WHERE TITULO='Design Patterns'), 'EJ-DP-1', 'DISPONIBLE', 'Estantería T2');

-- Hobbit
INSERT INTO biblioteca.EJEMPLAR (ID_LIBRO, CODIGO_BARRAS, ESTADO, UBICACION) VALUES ((SELECT ID_LIBRO FROM biblioteca.LIBRO WHERE TITULO='The Hobbit'), 'EJ-HOB-1', 'DISPONIBLE', 'Estantería F2');
INSERT INTO biblioteca.EJEMPLAR (ID_LIBRO, CODIGO_BARRAS, ESTADO, UBICACION) VALUES ((SELECT ID_LIBRO FROM biblioteca.LIBRO WHERE TITULO='The Hobbit'), 'EJ-HOB-2', 'PRESTADO', 'Estantería F2'); -- One borrowed

-- 3. History for Socio1 (ID usually 3, but let's look it up)
-- We want socio1 to have read Sci-Fi and Tech so Gemini recommends similar.
-- We need to insert into PRESTAMO with ESTADO='DEVUELTO'

-- Prestamo 1: Dune (ID 3)
INSERT INTO biblioteca.PRESTAMO (ID_SOCIO, ID_EJEMPLAR, FECHA_PRESTAMO, FECHA_PREVISTA_DEVOLUCION, FECHA_DEVOLUCION_REAL, ESTADO)
VALUES (
    (SELECT ID_SOCIO FROM biblioteca.SOCIO WHERE USUARIO='socio1'),
    (SELECT ID_EJEMPLAR FROM biblioteca.EJEMPLAR WHERE CODIGO_BARRAS='EJ-004'), -- Dune
    SYSDATE - 60,
    SYSDATE - 45,
    SYSDATE - 50,
    'DEVUELTO'
);

-- Prestamo 2: Effective Java (ID 1)
INSERT INTO biblioteca.PRESTAMO (ID_SOCIO, ID_EJEMPLAR, FECHA_PRESTAMO, FECHA_PREVISTA_DEVOLUCION, FECHA_DEVOLUCION_REAL, ESTADO)
VALUES (
    (SELECT ID_SOCIO FROM biblioteca.SOCIO WHERE USUARIO='socio1'),
    (SELECT ID_EJEMPLAR FROM biblioteca.EJEMPLAR WHERE CODIGO_BARRAS='EJ-001'), -- Effective Java
    SYSDATE - 30,
    SYSDATE - 15,
    SYSDATE - 20,
    'DEVUELTO'
);

COMMIT;



-- ==========================================
-- db/07_massive_seed.sql
-- ==========================================

-- Massive Seed Data

-- Novela
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-N01', 'Cien Años de Soledad', 'Gabriel García Márquez', 'Novela', 1967);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-N02', 'La Sombra del Viento', 'Carlos Ruiz Zafón', 'Novela', 2001);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-N03', 'El Código Da Vinci', 'Dan Brown', 'Novela', 2003);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-N04', 'Los Pilares de la Tierra', 'Ken Follett', 'Novela', 1989);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-N05', 'El Nombre de la Rosa', 'Umberto Eco', 'Novela', 1980);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-N06', 'Crónica de una Muerte Anunciada', 'Gabriel García Márquez', 'Novela', 1981);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-N07', 'La Casa de los Espíritus', 'Isabel Allende', 'Novela', 1982);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-N08', 'Don Quijote de la Mancha', 'Miguel de Cervantes', 'Novela', 1605);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-N09', 'El Amor en los Tiempos del Cólera', 'Gabriel García Márquez', 'Novela', 1985);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-N10', 'Fahrenheit 451', 'Ray Bradbury', 'Novela', 1953);

-- Ciencia Ficción / Fantasía
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-F01', 'Dune', 'Frank Herbert', 'Ciencia Ficción', 1965);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-F02', 'Neuromante', 'William Gibson', 'Ciencia Ficción', 1984);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-F03', 'Fundación', 'Isaac Asimov', 'Ciencia Ficción', 1951);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-F04', 'El Juego de Ender', 'Orson Scott Card', 'Ciencia Ficción', 1985);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-F05', 'Un Mundo Feliz', 'Aldous Huxley', 'Ciencia Ficción', 1932);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-F06', 'El Señor de los Anillos: La Comunidad del Anillo', 'J.R.R. Tolkien', 'Fantasía', 1954);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-F07', 'Harry Potter y la Piedra Filosofal', 'J.K. Rowling', 'Fantasía', 1997);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-F08', 'Juego de Tronos', 'George R.R. Martin', 'Fantasía', 1996);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-F09', 'El Nombre del Viento', 'Patrick Rothfuss', 'Fantasía', 2007);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-F10', 'American Gods', 'Neil Gaiman', 'Fantasía', 2001);

-- Tecnología
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-T01', 'The Pragmatic Programmer', 'Andrew Hunt', 'Tecnología', 1999);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-T02', 'Introduction to Algorithms', 'Thomas H. Cormen', 'Tecnología', 1990);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-T03', 'Refactoring', 'Martin Fowler', 'Tecnología', 1999);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-T04', 'Head First Design Patterns', 'Eric Freeman', 'Tecnología', 2004);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-T05', 'You Dont Know JS', 'Kyle Simpson', 'Tecnología', 2015);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-T06', 'Code Complete', 'Steve McConnell', 'Tecnología', 1993);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-T07', 'The Mythical Man-Month', 'Fred Brooks', 'Tecnología', 1975);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-T08', 'Designing Data-Intensive Applications', 'Martin Kleppmann', 'Tecnología', 2017);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-T09', 'Sapiens: De animales a dioses', 'Yuval Noah Harari', 'Historia', 2011);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-T10', 'Homo Deus', 'Yuval Noah Harari', 'Historia', 2015);

-- Historia / Biografía
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-H01', 'Steve Jobs', 'Walter Isaacson', 'Biografía', 2011);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-H02', 'Elon Musk', 'Walter Isaacson', 'Biografía', 2023);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-H03', 'Una Breve Historia de Casi Todo', 'Bill Bryson', 'Ciencia', 2003);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-H04', 'Cosmos', 'Carl Sagan', 'Ciencia', 1980);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-H05', 'El Gen Egoísta', 'Richard Dawkins', 'Ciencia', 1976);

-- Ejemplares (Copies) - 1 for each new book
INSERT INTO biblioteca.EJEMPLAR (ID_LIBRO, CODIGO_BARRAS, ESTADO, UBICACION) 
SELECT ID_LIBRO, 'EJ-' || ISBN, 'DISPONIBLE', 'Almacén General' 
FROM biblioteca.LIBRO 
WHERE ID_LIBRO NOT IN (SELECT ID_LIBRO FROM biblioteca.EJEMPLAR);

COMMIT;



-- ==========================================
-- db/08_jobs.sql
-- ==========================================

-- ==========================================
-- 4. JOB DE LIMPIEZA AUTOMÁTICA
-- ==========================================

-- Procedimiento almacenado para la limpieza
CREATE OR REPLACE PROCEDURE biblioteca.PROC_LIMPIEZA_BLOQUEOS AS
BEGIN
    -- 1. Marcar como EXPIRADO los bloqueos vencidos
    -- Se hace un cursor implícito para actualizar
    FOR r IN (
        SELECT ID_BLOQUEO, ID_EJEMPLAR
        FROM biblioteca.BLOQUEO
        WHERE ESTADO = 'ACTIVO'
          AND FECHA_FIN < SYSDATE
    ) LOOP
        -- Actualizar bloqueo
        UPDATE biblioteca.BLOQUEO SET ESTADO = 'EXPIRADO'
        WHERE ID_BLOQUEO = r.ID_BLOQUEO;

        -- Liberar ejemplar (volver a DISPONIBLE)
        -- Solo si no está prestado (aunque si el bloqueo estaba activo, debería estar BLOQUEADO)
        UPDATE biblioteca.EJEMPLAR SET ESTADO = 'DISPONIBLE'
        WHERE ID_EJEMPLAR = r.ID_EJEMPLAR
          AND ESTADO = 'BLOQUEADO';
    END LOOP;
    
    COMMIT;
END;
/

-- Crear el JOB programado (para ejecutar cada día a las 23:59)
BEGIN
    DBMS_SCHEDULER.CREATE_JOB (
        job_name        => 'JOB_LIMPIEZA_BLOQUEOS_DIARIA',
        job_type        => 'PLSQL_BLOCK',
        job_action      => 'BEGIN PROC_LIMPIEZA_BLOQUEOS; END;',
        start_date      => SYSTIMESTAMP,
        repeat_interval => 'FREQ=DAILY; BYHOUR=23; BYMINUTE=59; BYSECOND=0',
        enabled         => TRUE
    );
END;
/



-- ==========================================
-- db/09_cleanup_socio1.sql
-- ==========================================

-- Clean up multiple active blocks for socio1 (keep none or latest)
UPDATE biblioteca.BLOQUEO SET ESTADO = 'CANCELADO' 
WHERE ID_SOCIO = (SELECT ID_SOCIO FROM biblioteca.SOCIO WHERE USUARIO = 'socio1') 
  AND ESTADO = 'ACTIVO';

-- Reset Exemplar status to DISPONIBLE for those we just cancelled
-- Note: This is a bit rough, ideally we join. But let's just reset blocked items that are not in an active block.
UPDATE biblioteca.EJEMPLAR SET ESTADO = 'DISPONIBLE' 
WHERE ESTADO = 'BLOQUEADO' 
  AND ID_EJEMPLAR NOT IN (SELECT ID_EJEMPLAR FROM biblioteca.BLOQUEO WHERE ESTADO = 'ACTIVO');

COMMIT;



-- ==========================================
-- db/10_fix_version_column.sql
-- ==========================================

-- ==========================================
-- FIX: Agregar columna VERSION a tabla EJEMPLAR
-- Requerida para el control de concurrencia optimista (JPA @Version)
-- Fecha: 2026-01-19
-- ==========================================

-- Agregar columna VERSION a la tabla EJEMPLAR
ALTER TABLE biblioteca.EJEMPLAR ADD (VERSION NUMBER DEFAULT 0);

-- Actualizar registros existentes a versión 0
UPDATE biblioteca.EJEMPLAR SET VERSION = 0 WHERE VERSION IS NULL;

-- Opcional: Hacer la columna NOT NULL después de inicializar
-- ALTER TABLE biblioteca.EJEMPLAR MODIFY (VERSION NOT NULL);

COMMIT;

-- Verificación
SELECT ID_EJEMPLAR, CODIGO_BARRAS, ESTADO, VERSION FROM EJEMPLAR;


