-- ==========================================
-- SCRIPT MAESTRO DE INICIALIZACIÓN (GOLD MASTER v5 - DEMO MASSIVE DATA)
-- BiblioTech Pro - VPS Edition 
-- ==========================================

ALTER SESSION SET CONTAINER=XEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = biblioteca;
GRANT UNLIMITED TABLESPACE TO biblioteca;
GRANT CREATE JOB TO biblioteca;

-- 1. LIMPIEZA TOTAL
BEGIN
    FOR r IN (SELECT table_name FROM all_tables WHERE owner = 'BIBLIOTECA') LOOP
        EXECUTE IMMEDIATE 'DROP TABLE BIBLIOTECA.' || r.table_name || ' CASCADE CONSTRAINTS';
    END LOOP;
    FOR s IN (SELECT sequence_name FROM all_sequences WHERE sequence_owner = 'BIBLIOTECA') LOOP
        EXECUTE IMMEDIATE 'DROP SEQUENCE BIBLIOTECA.' || s.sequence_name;
    END LOOP;
    BEGIN DBMS_SCHEDULER.DROP_JOB('JOB_LIMPIEZA_BLOQUEOS'); EXCEPTION WHEN OTHERS THEN NULL; END;
END;
/

-- 2. ESTRUCTURA (DDL)
CREATE SEQUENCE biblioteca.SEQ_SOCIO START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE biblioteca.SEQ_LIBRO START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE biblioteca.SEQ_EJEMPLAR START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE biblioteca.SEQ_PRESTAMO START WITH 100 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE biblioteca.SEQ_BLOQUEO START WITH 100 INCREMENT BY 1 NOCACHE;

CREATE TABLE biblioteca.SOCIO (
    ID_SOCIO NUMBER DEFAULT biblioteca.SEQ_SOCIO.NEXTVAL PRIMARY KEY,
    USUARIO VARCHAR2(50) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR2(255) NOT NULL,
    ROL VARCHAR2(20) CHECK (ROL IN ('SOCIO', 'BIBLIOTECARIO', 'ADMIN')) NOT NULL,
    PENALIZACION_HASTA DATE,
    MAX_PRESTAMOS_ACTIVOS NUMBER DEFAULT 1 NOT NULL,
    NOMBRE VARCHAR2(100),
    EMAIL VARCHAR2(100)
);

CREATE TABLE biblioteca.LIBRO (
    ID_LIBRO NUMBER DEFAULT biblioteca.SEQ_LIBRO.NEXTVAL PRIMARY KEY,
    ISBN VARCHAR2(20) UNIQUE NOT NULL,
    TITULO VARCHAR2(200) NOT NULL,
    AUTOR VARCHAR2(100) NOT NULL,
    CATEGORIA VARCHAR2(50),
    ANIO NUMBER(4)
);

CREATE TABLE biblioteca.EJEMPLAR (
    ID_EJEMPLAR NUMBER DEFAULT biblioteca.SEQ_EJEMPLAR.NEXTVAL PRIMARY KEY,
    ID_LIBRO NUMBER NOT NULL,
    CODIGO_BARRAS VARCHAR2(50) UNIQUE NOT NULL,
    ESTADO VARCHAR2(20) CHECK (ESTADO IN ('DISPONIBLE', 'BLOQUEADO', 'PRESTADO', 'BAJA')) NOT NULL,
    UBICACION VARCHAR2(100),
    VERSION NUMBER DEFAULT 0,
    CONSTRAINT FK_EJEMPLAR_LIBRO FOREIGN KEY (ID_LIBRO) REFERENCES biblioteca.LIBRO(ID_LIBRO)
);

CREATE TABLE biblioteca.BLOQUEO (
    ID_BLOQUEO NUMBER DEFAULT biblioteca.SEQ_BLOQUEO.NEXTVAL PRIMARY KEY,
    ID_SOCIO NUMBER NOT NULL,
    ID_EJEMPLAR NUMBER NOT NULL,
    FECHA_INICIO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FECHA_FIN TIMESTAMP NOT NULL,
    ESTADO VARCHAR2(20) CHECK (ESTADO IN ('ACTIVO', 'CANCELADO', 'EXPIRADO', 'CONVERTIDO')) NOT NULL,
    CONSTRAINT FK_BLOQUEO_SOCIO FOREIGN KEY (ID_SOCIO) REFERENCES biblioteca.SOCIO(ID_SOCIO),
    CONSTRAINT FK_BLOQUEO_EJEMPLAR FOREIGN KEY (ID_EJEMPLAR) REFERENCES biblioteca.EJEMPLAR(ID_EJEMPLAR)
);

CREATE TABLE biblioteca.PRESTAMO (
    ID_PRESTAMO NUMBER DEFAULT biblioteca.SEQ_PRESTAMO.NEXTVAL PRIMARY KEY,
    ID_SOCIO NUMBER NOT NULL,
    ID_EJEMPLAR NUMBER NOT NULL,
    FECHA_PRESTAMO DATE DEFAULT SYSDATE NOT NULL,
    FECHA_PREVISTA_DEVOLUCION DATE NOT NULL,
    FECHA_DEVOLUCION_REAL DATE,
    ESTADO VARCHAR2(20) CHECK (ESTADO IN ('ACTIVO', 'DEVUELTO')) NOT NULL,
    ID_BLOQUEO NUMBER,
    CONSTRAINT FK_PRESTAMO_SOCIO FOREIGN KEY (ID_SOCIO) REFERENCES biblioteca.SOCIO(ID_SOCIO),
    CONSTRAINT FK_PRESTAMO_EJEMPLAR FOREIGN KEY (ID_EJEMPLAR) REFERENCES biblioteca.EJEMPLAR(ID_EJEMPLAR),
    CONSTRAINT FK_PRESTAMO_BLOQUEO FOREIGN KEY (ID_BLOQUEO) REFERENCES biblioteca.BLOQUEO(ID_BLOQUEO)
);

CREATE UNIQUE INDEX biblioteca.IDX_UN_BLOQUEO_ACTIVO ON biblioteca.BLOQUEO (CASE WHEN ESTADO = 'ACTIVO' THEN ID_SOCIO ELSE NULL END);

-- 3. PROCEDURES
CREATE OR REPLACE PROCEDURE biblioteca.SP_LIMPIEZA_DIARIA IS
BEGIN
    FOR r IN (SELECT b.ID_BLOQUEO, b.ID_EJEMPLAR FROM biblioteca.BLOQUEO b WHERE b.ESTADO = 'ACTIVO' AND b.FECHA_FIN < SYSDATE) LOOP
        UPDATE biblioteca.BLOQUEO SET ESTADO = 'EXPIRADO' WHERE ID_BLOQUEO = r.ID_BLOQUEO;
        UPDATE biblioteca.EJEMPLAR SET ESTADO = 'DISPONIBLE' WHERE ID_EJEMPLAR = r.ID_EJEMPLAR;
    END LOOP;
    COMMIT;
END;
/

-- 4. TRIGGERS
CREATE OR REPLACE TRIGGER biblioteca.TRG_VALIDAR_BLOQUEO_INSERT
BEFORE INSERT ON biblioteca.BLOQUEO
FOR EACH ROW
DECLARE
    v_bloqueos_activos NUMBER;
    v_estado_ejemplar VARCHAR2(20);
BEGIN
    SELECT COUNT(*) INTO v_bloqueos_activos FROM biblioteca.BLOQUEO WHERE ID_SOCIO = :NEW.ID_SOCIO AND ESTADO = 'ACTIVO';
    IF v_bloqueos_activos > 0 THEN RAISE_APPLICATION_ERROR(-20101, 'El socio ya tiene un bloqueo activo.'); END IF;
    SELECT ESTADO INTO v_estado_ejemplar FROM biblioteca.EJEMPLAR WHERE ID_EJEMPLAR = :NEW.ID_EJEMPLAR;
    IF v_estado_ejemplar != 'DISPONIBLE' THEN RAISE_APPLICATION_ERROR(-20102, 'El ejemplar no esta disponible'); END IF;
END;
/
CREATE OR REPLACE TRIGGER biblioteca.TRG_ACTUALIZAR_ESTADO_BLOQUEO AFTER INSERT ON biblioteca.BLOQUEO FOR EACH ROW BEGIN UPDATE biblioteca.EJEMPLAR SET ESTADO = 'BLOQUEADO' WHERE ID_EJEMPLAR = :NEW.ID_EJEMPLAR; END;
/

CREATE OR REPLACE TRIGGER biblioteca.TRG_VALIDAR_PRESTAMO
BEFORE INSERT ON biblioteca.PRESTAMO
FOR EACH ROW
DECLARE
    v_penalizacion DATE; v_num NUMBER; v_max NUMBER; v_est VARCHAR2(20); v_id_bloq NUMBER;
BEGIN
    SELECT PENALIZACION_HASTA, MAX_PRESTAMOS_ACTIVOS INTO v_penalizacion, v_max FROM biblioteca.SOCIO WHERE ID_SOCIO = :NEW.ID_SOCIO;
    IF v_penalizacion > SYSDATE THEN RAISE_APPLICATION_ERROR(-20001, 'Socio penalizado'); END IF;
    SELECT COUNT(*) INTO v_num FROM biblioteca.PRESTAMO WHERE ID_SOCIO = :NEW.ID_SOCIO AND ESTADO = 'ACTIVO';
    IF v_num >= v_max THEN RAISE_APPLICATION_ERROR(-20002, 'Limite de prestamos superado'); END IF;
    SELECT ESTADO INTO v_est FROM biblioteca.EJEMPLAR WHERE ID_EJEMPLAR = :NEW.ID_EJEMPLAR;
    IF v_est IN ('PRESTADO', 'BAJA') THEN RAISE_APPLICATION_ERROR(-20003, 'Ejemplar no disponible'); END IF;
    IF v_est = 'BLOQUEADO' THEN
         BEGIN
             SELECT ID_BLOQUEO INTO v_id_bloq FROM biblioteca.BLOQUEO WHERE ID_EJEMPLAR = :NEW.ID_EJEMPLAR AND ID_SOCIO = :NEW.ID_SOCIO AND ESTADO = 'ACTIVO';
             IF :NEW.ID_BLOQUEO IS NULL THEN :NEW.ID_BLOQUEO := v_id_bloq; END IF;
         EXCEPTION WHEN NO_DATA_FOUND THEN RAISE_APPLICATION_ERROR(-20004, 'Ejemplar bloqueado por otro'); END;
    END IF;
END;
/
CREATE OR REPLACE TRIGGER biblioteca.TRG_PRESTAMO_POST_INSERT AFTER INSERT ON biblioteca.PRESTAMO FOR EACH ROW BEGIN UPDATE biblioteca.EJEMPLAR SET ESTADO = 'PRESTADO' WHERE ID_EJEMPLAR = :NEW.ID_EJEMPLAR; IF :NEW.ID_BLOQUEO IS NOT NULL THEN UPDATE biblioteca.BLOQUEO SET ESTADO = 'CONVERTIDO' WHERE ID_BLOQUEO = :NEW.ID_BLOQUEO; END IF; END;
/

-- 5. JOB
BEGIN
    DBMS_SCHEDULER.CREATE_JOB (
        job_name => 'JOB_LIMPIEZA_BLOQUEOS',
        job_type => 'PLSQL_BLOCK',
        job_action => 'BEGIN biblioteca.SP_LIMPIEZA_DIARIA; END;',
        start_date => SYSTIMESTAMP,
        repeat_interval => 'FREQ=DAILY; BYHOUR=23; BYMINUTE=59; BYSECOND=0',
        enabled => TRUE
    );
END;
/

-- 6. DATOS MASIVOS (CARGA DEMO)
-- =====================================

-- ==== USUARIOS ====
-- Password 'password'
INSERT INTO biblioteca.SOCIO (USUARIO, PASSWORD_HASH, ROL, NOMBRE, EMAIL, MAX_PRESTAMOS_ACTIVOS) VALUES ('admin', '$2a$10$BA0QvPo6W1sgf2kx7g9C/ulfV.CI8lmDJ/HJczwPrEtOPPAwsePdW', 'ADMIN', 'Super Admin', 'admin@bibliotech.com', 10);
INSERT INTO biblioteca.SOCIO (USUARIO, PASSWORD_HASH, ROL, NOMBRE, EMAIL, MAX_PRESTAMOS_ACTIVOS) VALUES ('biblio', '$2a$10$BA0QvPo6W1sgf2kx7g9C/ulfV.CI8lmDJ/HJczwPrEtOPPAwsePdW', 'BIBLIOTECARIO', 'Maria Bibliotecaria', 'biblio@bibliotech.com', 10);
INSERT INTO biblioteca.SOCIO (USUARIO, PASSWORD_HASH, ROL, NOMBRE, EMAIL, MAX_PRESTAMOS_ACTIVOS) VALUES ('socio1', '$2a$10$BA0QvPo6W1sgf2kx7g9C/ulfV.CI8lmDJ/HJczwPrEtOPPAwsePdW', 'SOCIO', 'Juan Perez', 'juan@mail.com', 3);
INSERT INTO biblioteca.SOCIO (USUARIO, PASSWORD_HASH, ROL, NOMBRE, EMAIL, MAX_PRESTAMOS_ACTIVOS) VALUES ('socio2', '$2a$10$BA0QvPo6W1sgf2kx7g9C/ulfV.CI8lmDJ/HJczwPrEtOPPAwsePdW', 'SOCIO', 'Ana Gomez', 'ana@mail.com', 3);
INSERT INTO biblioteca.SOCIO (USUARIO, PASSWORD_HASH, ROL, NOMBRE, EMAIL, MAX_PRESTAMOS_ACTIVOS) VALUES ('socio3', '$2a$10$BA0QvPo6W1sgf2kx7g9C/ulfV.CI8lmDJ/HJczwPrEtOPPAwsePdW', 'SOCIO', 'Carlos Ruiz', 'carlos@mail.com', 5);
INSERT INTO biblioteca.SOCIO (USUARIO, PASSWORD_HASH, ROL, NOMBRE, EMAIL, MAX_PRESTAMOS_ACTIVOS) VALUES ('socio4', '$2a$10$BA0QvPo6W1sgf2kx7g9C/ulfV.CI8lmDJ/HJczwPrEtOPPAwsePdW', 'SOCIO', 'Laura Diaz', 'laura@mail.com', 3);
INSERT INTO biblioteca.SOCIO (USUARIO, PASSWORD_HASH, ROL, NOMBRE, EMAIL, MAX_PRESTAMOS_ACTIVOS) VALUES ('invitado', '$2a$10$BA0QvPo6W1sgf2kx7g9C/ulfV.CI8lmDJ/HJczwPrEtOPPAwsePdW', 'SOCIO', 'Visitante Demo', 'demo@mail.com', 1);

-- ==== LIBROS (Con ISBNs reales para OpenLibrary) ====

-- FANTASÍA (Frontend: Fantasía)
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('9780547928227', 'The Hobbit', 'J.R.R. Tolkien', 'Fantasía', 1937);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('9780261102385', 'The Lord of the Rings', 'J.R.R. Tolkien', 'Fantasía', 1954);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('9780439554930', 'Harry Potter and the Sorcerers Stone', 'J.K. Rowling', 'Fantasía', 1997);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('9780553109535', 'A Game of Thrones', 'George R.R. Martin', 'Fantasía', 1996);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('9780756404079', 'The Name of the Wind', 'Patrick Rothfuss', 'Fantasía', 2007);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('9780062059880', 'American Gods', 'Neil Gaiman', 'Fantasía', 2001);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('9780345339683', 'The Silmarillion', 'J.R.R. Tolkien', 'Fantasía', 1977);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('9780143111555', 'The Magicians', 'Lev Grossman', 'Fantasía', 2009);

-- CIENCIA FICCIÓN (Frontend: Ciencia Ficción)
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('9780441013593', 'Dune', 'Frank Herbert', 'Ciencia Ficción', 1965);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('9780553293357', 'Foundation', 'Isaac Asimov', 'Ciencia Ficción', 1951);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('9780345391803', 'The Hitchhikers Guide to the Galaxy', 'Douglas Adams', 'Ciencia Ficción', 1979);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('9780765301515', 'Enders Game', 'Orson Scott Card', 'Ciencia Ficción', 1985);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('9780441569595', 'Neuromancer', 'William Gibson', 'Ciencia Ficción', 1984);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('9780553382563', 'I, Robot', 'Isaac Asimov', 'Ciencia Ficción', 1950);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('9780307292063', 'The Martian', 'Andy Weir', 'Ciencia Ficción', 2011);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('9780451526342', 'The Time Machine', 'H.G. Wells', 'Ciencia Ficción', 1895);

-- NOVELA (Frontend: Novela)
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('9780451524935', '1984', 'George Orwell', 'Novela', 1949);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('9780743273565', 'The Great Gatsby', 'F. Scott Fitzgerald', 'Novela', 1925);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('9780307474278', 'The Da Vinci Code', 'Dan Brown', 'Novela', 2003);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('9780345806789', 'The Shining Girls', 'Lauren Beukes', 'Novela', 2013);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('9781400033416', 'Beloved', 'Toni Morrison', 'Novela', 1987);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('9780307277671', 'The Brief Wondrous Life of Oscar Wao', 'Junot Diaz', 'Novela', 2007);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('9780307387899', 'The Road', 'Cormac McCarthy', 'Novela', 2006);

-- CLÁSICOS (Frontend has no explicit filter usually, mapped to Novela or distinct?)
-- Frontend filter has: Novela, Ciencia Ficción, Fantasía, Biografía, Historia, Tecnología.
-- We will map Clasicos to Novela for better UX in this specific frontend, or keep as Clasicos if "Todas" is used.
-- Let's use 'Novela' for these to populate that category more, or 'Historia' if appropriate.
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('9780141439518', 'Pride and Prejudice', 'Jane Austen', 'Novela', 1813); 
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('9780061120084', 'To Kill a Mockingbird', 'Harper Lee', 'Novela', 1960);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('9780140449136', 'Crime and Punishment', 'Fyodor Dostoevsky', 'Novela', 1866);

-- TECNOLOGÍA (Frontend: Tecnología)
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('9780134685991', 'Effective Java', 'Joshua Bloch', 'Tecnología', 2018);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('9780132350884', 'Clean Code', 'Robert C. Martin', 'Tecnología', 2008);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('9780201633610', 'Design Patterns', 'Erich Gamma', 'Tecnología', 1994);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('9781449331818', 'Learning Python', 'Mark Lutz', 'Tecnología', 2013);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('9780131103627', 'The C Programming Language', 'Brian Kernighan', 'Tecnología', 1978);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('9780321125217', 'Domain-Driven Design', 'Eric Evans', 'Tecnología', 2003);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('9781491950357', 'Building Microservices', 'Sam Newman', 'Tecnología', 2015);

-- HISTORIA (Frontend: Historia)
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('9781400064168', 'Sapiens', 'Yuval Noah Harari', 'Historia', 2011);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('9780141032009', 'Guns, Germs, and Steel', 'Jared Diamond', 'Historia', 1997);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('9780140280197', 'The 48 Laws of Power', 'Robert Greene', 'Historia', 1998);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('9780679603348', 'The Histories', 'Herodotus', 'Historia', -440);

-- BIOGRAFÍA (Frontend: Biografía)
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('9781501127625', 'Steve Jobs', 'Walter Isaacson', 'Biografía', 2011);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('9780553381696', 'A Brief History of Time', 'Stephen Hawking', 'Biografía', 1988);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('9781101911860', 'Elon Musk', 'Ashlee Vance', 'Biografía', 2015);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('9780425287521', 'Shoe Dog', 'Phil Knight', 'Biografía', 2016);

-- ==== EJEMPLARES (Generación Masiva) ====

BEGIN
    -- Generar 3 copias para todos los libros
    FOR b IN (SELECT ID_LIBRO, ISBN FROM biblioteca.LIBRO) LOOP
        FOR i IN 1..3 LOOP
            INSERT INTO biblioteca.EJEMPLAR (ID_LIBRO, CODIGO_BARRAS, ESTADO, UBICACION)
            VALUES (b.ID_LIBRO, 'EJ-' || SUBSTR(b.ISBN, -6) || '-' || i, 'DISPONIBLE', 'Estanteria ' || MOD(b.ID_LIBRO, 5));
        END LOOP;
    END LOOP;
END;
/

-- Ajustes manuales para Demo (Algunos prestados, algunos reservados)



-- Insertar Historico de Prestamos (Para graficas)
INSERT INTO biblioteca.PRESTAMO (ID_SOCIO, ID_EJEMPLAR, FECHA_PRESTAMO, FECHA_PREVISTA_DEVOLUCION, FECHA_DEVOLUCION_REAL, ESTADO)
VALUES ((SELECT ID_SOCIO FROM biblioteca.SOCIO WHERE USUARIO='socio1'), (SELECT ID_EJEMPLAR FROM biblioteca.EJEMPLAR WHERE CODIGO_BARRAS LIKE '%4930-1'), SYSDATE - 30, SYSDATE - 15, SYSDATE - 16, 'DEVUELTO');

INSERT INTO biblioteca.PRESTAMO (ID_SOCIO, ID_EJEMPLAR, FECHA_PRESTAMO, FECHA_PREVISTA_DEVOLUCION, FECHA_DEVOLUCION_REAL, ESTADO)
VALUES ((SELECT ID_SOCIO FROM biblioteca.SOCIO WHERE USUARIO='socio2'), (SELECT ID_EJEMPLAR FROM biblioteca.EJEMPLAR WHERE CODIGO_BARRAS LIKE '%4930-3'), SYSDATE - 6, SYSDATE + 9, NULL, 'ACTIVO');

-- Activar el préstamo actual de Harry Potter 1 (que marcamos como prestado arriba)
INSERT INTO biblioteca.PRESTAMO (ID_SOCIO, ID_EJEMPLAR, FECHA_PRESTAMO, FECHA_PREVISTA_DEVOLUCION, ESTADO)
VALUES ((SELECT ID_SOCIO FROM biblioteca.SOCIO WHERE USUARIO='socio3'), (SELECT ID_EJEMPLAR FROM biblioteca.EJEMPLAR WHERE CODIGO_BARRAS LIKE '%4930-1'), SYSDATE - 2, SYSDATE + 13, 'ACTIVO');

-- Crear el bloqueo activo para Clean Code
INSERT INTO biblioteca.BLOQUEO (ID_SOCIO, ID_EJEMPLAR, FECHA_INICIO, FECHA_FIN, ESTADO)
VALUES ((SELECT ID_SOCIO FROM biblioteca.SOCIO WHERE USUARIO='socio1'), (SELECT ID_EJEMPLAR FROM biblioteca.EJEMPLAR WHERE CODIGO_BARRAS LIKE '%0884-1'), SYSDATE, SYSDATE + 1, 'ACTIVO');

-- Prestamos Extra
INSERT INTO biblioteca.PRESTAMO (ID_SOCIO, ID_EJEMPLAR, FECHA_PRESTAMO, FECHA_PREVISTA_DEVOLUCION, ESTADO)
VALUES ((SELECT ID_SOCIO FROM biblioteca.SOCIO WHERE USUARIO='biblio'), (SELECT ID_EJEMPLAR FROM biblioteca.EJEMPLAR WHERE CODIGO_BARRAS LIKE '%4930-2'), SYSDATE - 1, SYSDATE + 14, 'ACTIVO');

INSERT INTO biblioteca.PRESTAMO (ID_SOCIO, ID_EJEMPLAR, FECHA_PRESTAMO, FECHA_PREVISTA_DEVOLUCION, ESTADO)
VALUES ((SELECT ID_SOCIO FROM biblioteca.SOCIO WHERE USUARIO='socio4'), (SELECT ID_EJEMPLAR FROM biblioteca.EJEMPLAR WHERE CODIGO_BARRAS LIKE '%1515-1'), SYSDATE - 5, SYSDATE + 10, 'ACTIVO');

COMMIT;
EXIT;
