-- ==========================================
-- SCRIPT DE DATOS DE DEMOSTRACIÓN (Masivo)
-- BiblioTech Pro
-- ==========================================

ALTER SESSION SET CURRENT_SCHEMA = biblioteca;

-- 1. USUARIOS ADICIONALES
-- Password para todos: "password"
-- ($2a$10$BA0QvPo6W1sgf2kx7g9C/ulfV.CI8lmDJ/HJczwPrEtOPPAwsePdW)

INSERT INTO biblioteca.SOCIO (USUARIO, PASSWORD_HASH, ROL, NOMBRE, EMAIL, MAX_PRESTAMOS_ACTIVOS) VALUES ('laura_g', '$2a$10$BA0QvPo6W1sgf2kx7g9C/ulfV.CI8lmDJ/HJczwPrEtOPPAwsePdW', 'SOCIO', 'Laura Garcia', 'laura@email.com', 3);
INSERT INTO biblioteca.SOCIO (USUARIO, PASSWORD_HASH, ROL, NOMBRE, EMAIL, MAX_PRESTAMOS_ACTIVOS) VALUES ('carlos_m', '$2a$10$BA0QvPo6W1sgf2kx7g9C/ulfV.CI8lmDJ/HJczwPrEtOPPAwsePdW', 'SOCIO', 'Carlos Martinez', 'carlos@email.com', 3);
INSERT INTO biblioteca.SOCIO (USUARIO, PASSWORD_HASH, ROL, NOMBRE, EMAIL, MAX_PRESTAMOS_ACTIVOS) VALUES ('sofia_l', '$2a$10$BA0QvPo6W1sgf2kx7g9C/ulfV.CI8lmDJ/HJczwPrEtOPPAwsePdW', 'SOCIO', 'Sofia Lopez', 'sofia@email.com', 3);
INSERT INTO biblioteca.SOCIO (USUARIO, PASSWORD_HASH, ROL, NOMBRE, EMAIL, MAX_PRESTAMOS_ACTIVOS) VALUES ('david_r', '$2a$10$BA0QvPo6W1sgf2kx7g9C/ulfV.CI8lmDJ/HJczwPrEtOPPAwsePdW', 'SOCIO', 'David Ruiz', 'david@email.com', 3);
INSERT INTO biblioteca.SOCIO (USUARIO, PASSWORD_HASH, ROL, NOMBRE, EMAIL, MAX_PRESTAMOS_ACTIVOS) VALUES ('ana_p', '$2a$10$BA0QvPo6W1sgf2kx7g9C/ulfV.CI8lmDJ/HJczwPrEtOPPAwsePdW', 'SOCIO', 'Ana Perez', 'ana@email.com', 3);
INSERT INTO biblioteca.SOCIO (USUARIO, PASSWORD_HASH, ROL, NOMBRE, EMAIL, MAX_PRESTAMOS_ACTIVOS) VALUES ('miguel_t', '$2a$10$BA0QvPo6W1sgf2kx7g9C/ulfV.CI8lmDJ/HJczwPrEtOPPAwsePdW', 'SOCIO', 'Miguel Torres', 'miguel@email.com', 5); -- VIP
INSERT INTO biblioteca.SOCIO (USUARIO, PASSWORD_HASH, ROL, NOMBRE, EMAIL, MAX_PRESTAMOS_ACTIVOS) VALUES ('elena_v', '$2a$10$BA0QvPo6W1sgf2kx7g9C/ulfV.CI8lmDJ/HJczwPrEtOPPAwsePdW', 'SOCIO', 'Elena Vega', 'elena@email.com', 3);

-- 2. LIBROS (Catálogo extendido)
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-84-01-02050-8', 'Dune', 'Frank Herbert', 'Ciencia Ficción', 1965);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-84-663-3292-0', 'El hombre en el castillo', 'Philip K. Dick', 'Ciencia Ficción', 1962);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-84-9838-706-3', 'Cien años de soledad', 'Gabriel García Márquez', 'Novela', 1967);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-84-376-0494-7', 'Don Quijote de la Mancha', 'Miguel de Cervantes', 'Clásico', 1605);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-0-321-12521-7', 'Domain-Driven Design', 'Eric Evans', 'Tecnología', 2003);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-0-13-235088-4', 'Clean Code', 'Robert C. Martin', 'Tecnología', 2008);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-84-666-5973-4', 'Sapiens: De animales a dioses', 'Yuval Noah Harari', 'Historia', 2011);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-84-339-7964-0', 'Los detectives salvajes', 'Roberto Bolaño', 'Novela', 1998);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-84-96208-67-4', 'El nombre del viento', 'Patrick Rothfuss', 'Fantasía', 2007);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-84-450-7708-5', 'El Silmarillion', 'J.R.R. Tolkien', 'Fantasía', 1977);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-1-491-95035-7', 'Building Microservices', 'Sam Newman', 'Tecnología', 2015);
INSERT INTO biblioteca.LIBRO (ISBN, TITULO, AUTOR, CATEGORIA, ANIO) VALUES ('978-84-322-1923-8', 'La sombra del viento', 'Carlos Ruiz Zafón', 'Misterio', 2001);

-- 3. EJEMPLARES (2-3 copias por libro nuevo)
-- Dune
INSERT INTO biblioteca.EJEMPLAR (ID_LIBRO, CODIGO_BARRAS, ESTADO, UBICACION) VALUES ((SELECT ID_LIBRO FROM biblioteca.LIBRO WHERE TITULO='Dune'), 'EJ-DUNE-1', 'DISPONIBLE', 'Estantería CF-1');
INSERT INTO biblioteca.EJEMPLAR (ID_LIBRO, CODIGO_BARRAS, ESTADO, UBICACION) VALUES ((SELECT ID_LIBRO FROM biblioteca.LIBRO WHERE TITULO='Dune'), 'EJ-DUNE-2', 'PRESTADO', 'Estantería CF-1'); -- Prestado a Carlos

-- Cien años
INSERT INTO biblioteca.EJEMPLAR (ID_LIBRO, CODIGO_BARRAS, ESTADO, UBICACION) VALUES ((SELECT ID_LIBRO FROM biblioteca.LIBRO WHERE TITULO='Cien años de soledad'), 'EJ-CIEN-1', 'DISPONIBLE', 'Estantería N-2');
INSERT INTO biblioteca.EJEMPLAR (ID_LIBRO, CODIGO_BARRAS, ESTADO, UBICACION) VALUES ((SELECT ID_LIBRO FROM biblioteca.LIBRO WHERE TITULO='Cien años de soledad'), 'EJ-CIEN-2', 'DISPONIBLE', 'Estantería N-2');

-- Clean Code
INSERT INTO biblioteca.EJEMPLAR (ID_LIBRO, CODIGO_BARRAS, ESTADO, UBICACION) VALUES ((SELECT ID_LIBRO FROM biblioteca.LIBRO WHERE TITULO='Clean Code'), 'EJ-CLEAN-1', 'DISPONIBLE', 'Estantería T-5');
INSERT INTO biblioteca.EJEMPLAR (ID_LIBRO, CODIGO_BARRAS, ESTADO, UBICACION) VALUES ((SELECT ID_LIBRO FROM biblioteca.LIBRO WHERE TITULO='Clean Code'), 'EJ-CLEAN-2', 'PRESTADO', 'Estantería T-5'); -- Prestado a Superdev

-- El nombre del viento
INSERT INTO biblioteca.EJEMPLAR (ID_LIBRO, CODIGO_BARRAS, ESTADO, UBICACION) VALUES ((SELECT ID_LIBRO FROM biblioteca.LIBRO WHERE TITULO='El nombre del viento'), 'EJ-VIENTO-1', 'BLOQUEADO', 'Estantería F-3'); -- Reservado por Sofia

-- Sapiens
INSERT INTO biblioteca.EJEMPLAR (ID_LIBRO, CODIGO_BARRAS, ESTADO, UBICACION) VALUES ((SELECT ID_LIBRO FROM biblioteca.LIBRO WHERE TITULO='Sapiens: De animales a dioses'), 'EJ-SAPIENS-1', 'DISPONIBLE', 'Estantería H-1');

-- Más ejemplares genéricos para bulto
INSERT INTO biblioteca.EJEMPLAR (ID_LIBRO, CODIGO_BARRAS, ESTADO, UBICACION) VALUES ((SELECT ID_LIBRO FROM biblioteca.LIBRO WHERE TITULO='Domain-Driven Design'), 'EJ-DDD-1', 'DISPONIBLE', 'Estantería T-6');
INSERT INTO biblioteca.EJEMPLAR (ID_LIBRO, CODIGO_BARRAS, ESTADO, UBICACION) VALUES ((SELECT ID_LIBRO FROM biblioteca.LIBRO WHERE TITULO='La sombra del viento'), 'EJ-SOMBRA-1', 'DISPONIBLE', 'Estantería M-1');
INSERT INTO biblioteca.EJEMPLAR (ID_LIBRO, CODIGO_BARRAS, ESTADO, UBICACION) VALUES ((SELECT ID_LIBRO FROM biblioteca.LIBRO WHERE TITULO='La sombra del viento'), 'EJ-SOMBRA-2', 'DISPONIBLE', 'Estantería M-1');


-- 4. HISTORIAL Y MOVIMIENTOS
-- Prestamo activo: Dune -> Carlos
INSERT INTO biblioteca.PRESTAMO (ID_SOCIO, ID_EJEMPLAR, FECHA_PRESTAMO, FECHA_PREVISTA_DEVOLUCION, ESTADO)
VALUES (
    (SELECT ID_SOCIO FROM biblioteca.SOCIO WHERE USUARIO='carlos_m'),
    (SELECT ID_EJEMPLAR FROM biblioteca.EJEMPLAR WHERE CODIGO_BARRAS='EJ-DUNE-2'),
    SYSDATE - 5, SYSDATE + 10, 'ACTIVO'
);

-- Prestamo activo: Clean Code -> Superdev
INSERT INTO biblioteca.PRESTAMO (ID_SOCIO, ID_EJEMPLAR, FECHA_PRESTAMO, FECHA_PREVISTA_DEVOLUCION, ESTADO)
VALUES (
    (SELECT ID_SOCIO FROM biblioteca.SOCIO WHERE USUARIO='superdev'),
    (SELECT ID_EJEMPLAR FROM biblioteca.EJEMPLAR WHERE CODIGO_BARRAS='EJ-CLEAN-2'),
    SYSDATE - 2, SYSDATE + 13, 'ACTIVO'
);

-- Reserva activa: El nombre del viento -> Sofia
INSERT INTO biblioteca.BLOQUEO (ID_SOCIO, ID_EJEMPLAR, FECHA_INICIO, FECHA_FIN, ESTADO)
VALUES (
    (SELECT ID_SOCIO FROM biblioteca.SOCIO WHERE USUARIO='sofia_l'),
    (SELECT ID_EJEMPLAR FROM biblioteca.EJEMPLAR WHERE CODIGO_BARRAS='EJ-VIENTO-1'),
    SYSDATE, SYSDATE + 1, 'ACTIVO'
);

-- Historial pasado (Devueltos)
-- Laura leyó Cien años de soledad
INSERT INTO biblioteca.PRESTAMO (ID_SOCIO, ID_EJEMPLAR, FECHA_PRESTAMO, FECHA_PREVISTA_DEVOLUCION, FECHA_DEVOLUCION_REAL, ESTADO)
VALUES (
    (SELECT ID_SOCIO FROM biblioteca.SOCIO WHERE USUARIO='laura_g'),
    (SELECT ID_EJEMPLAR FROM biblioteca.EJEMPLAR WHERE CODIGO_BARRAS='EJ-CIEN-1'),
    SYSDATE - 60, SYSDATE - 45, SYSDATE - 48, 'DEVUELTO'
);

-- Admin leyó Clean Code
INSERT INTO biblioteca.PRESTAMO (ID_SOCIO, ID_EJEMPLAR, FECHA_PRESTAMO, FECHA_PREVISTA_DEVOLUCION, FECHA_DEVOLUCION_REAL, ESTADO)
VALUES (
    (SELECT ID_SOCIO FROM biblioteca.SOCIO WHERE USUARIO='admin'),
    (SELECT ID_EJEMPLAR FROM biblioteca.EJEMPLAR WHERE CODIGO_BARRAS='EJ-CLEAN-1'),
    SYSDATE - 100, SYSDATE - 85, SYSDATE - 90, 'DEVUELTO'
);

-- Carlos leyó Sapiens
INSERT INTO biblioteca.PRESTAMO (ID_SOCIO, ID_EJEMPLAR, FECHA_PRESTAMO, FECHA_PREVISTA_DEVOLUCION, FECHA_DEVOLUCION_REAL, ESTADO)
VALUES (
    (SELECT ID_SOCIO FROM biblioteca.SOCIO WHERE USUARIO='carlos_m'),
    (SELECT ID_EJEMPLAR FROM biblioteca.EJEMPLAR WHERE CODIGO_BARRAS='EJ-SAPIENS-1'),
    SYSDATE - 200, SYSDATE - 185, SYSDATE - 180, 'DEVUELTO'
);

COMMIT;
